version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'dadocu'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin1234'
      MYSQL_ROOT_PASSWORD: 'admin1234'
    ports:
      - '3306:3306'
    volumes:
      - './mysql-data:/var/lib/mysql'